apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-image
spec:
  params:
    - name: IMAGE
      type: string
  workspaces:
    - name: source
  steps:
    - name: build
      image: quay.io/buildah/stable
      securityContext:
        runAsUser: 1001
      workingDir: $(workspaces.source.path)
      script: |
        buildah bud -f Dockerfile -t $(params.IMAGE) .
        buildah push $(params.IMAGE)
