apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: maven-build
spec:
  workspaces:
    - name: source
   steps:
  - name: build
    image: maven:3.9.0-eclipse-temurin-17
    script: |
      #!/bin/sh
      cd /workspace/source/java-webapp
      mvn clean package
